export const defaultTheme = {
  colors: {
    bodyBackground: '#FFFFFF',
    mainBackground: '#FFFFFF',
    sectionBackground: '#F7F7F5',
    cardBackground: '#FFFFFF',
    primary: '#6B4F3B',
    secondary: '#B8A99A',
    accent: '#B89A6A',
    background: '#FFFFFF',
    surface: '#F5F0EA',
    text: '#222222',
    heading: '#181817',
    muted: '#8B8177',
    border: '#EBEBEB',
    buttonBackground: '#1A1A1A',
    buttonText: '#FFFFFF',
    buttonHover: '#333333',
    sale: '#E03D3D',
    saleText: '#FFFFFF',
    onPrimary: '#FFFFFF',
    link: '#6B4F3B',
    linkHover: '#513A2C',
    headerBackground: '#FFFFFF',
    headerText: '#222222',
    footerBackground: '#1C1C1A',
    footerText: '#F0EDE8',
    announcementBackground: '#1C1C1A',
    announcementText: '#F0EDE8',
    inputBackground: '#FFFFFF',
    inputBorder: '#E0E0E0',
    inputFocus: '#6B4F3B',
    error: '#DC2626',
    success: '#16A34A',
    wishlist: '#E05070',
  },
  fonts: {
    heading: "ui-serif, Georgia, 'Times New Roman', serif",
    body: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
  },
  layout: {
    containerWidth: '1280px',
    borderRadius: '8px',
    radiusButton: '8px',
    radiusCard: '12px',
    sectionSpacing: '3rem',
    productImageAspect: '4/5',
    headerStyle: 'default',
    footerStyle: 'default',
  },
}
