export const defaultTheme = {
  colors: {
    bodyBackground: '#F6F1EB',
    mainBackground: '#F6F1EB',
    sectionBackground: '#FBFAF7',
    cardBackground: '#FFFFFF',
    primary: '#6B4F3B',
    secondary: '#B8A99A',
    accent: '#B89A6A',
    background: '#F6F1EB',
    surface: '#F3EDE7',
    text: '#222222',
    heading: '#222222',
    muted: '#8B8177',
    border: '#E8E0D6',
    buttonBackground: '#6B4F3B',
    buttonText: '#F6F1EB',
    buttonHover: '#513A2C',
    sale: '#B89A6A',
    saleText: '#FFFFFF',
    onPrimary: '#F6F1EB',
    link: '#6B4F3B',
    linkHover: '#513A2C',
    headerBackground: '#FFFFFF',
    headerText: '#222222',
    footerBackground: '#292724',
    footerText: '#F6F1EB',
    announcementBackground: '#6B4F3B',
    announcementText: '#F6F1EB',
    inputBackground: '#FFFFFF',
    inputBorder: '#D8D0C6',
    inputFocus: '#6B4F3B',
    error: '#A33A32',
    success: '#3F6B4F',
    wishlist: '#9B4D55'
  },
  fonts: {
    heading: "ui-serif, Georgia, 'Times New Roman', serif",
    body: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial"
  },
  layout: {
    containerWidth: '1200px',
    borderRadius: '6px',
    radiusButton: '6px',
    radiusCard: '8px',
    sectionSpacing: '3rem',
    productImageAspect: '4/5',
    headerStyle: 'default',
    footerStyle: 'default'
  }
}
